### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
adapter_name_or_path: qwen2_5_vl_lora_indexing_1

template: qwen2_vl
finetuning_type: lora

### export
export_dir: models/llama3_lora_sft
export_size: 2
export_device: cpu
export_legacy_format: false